#!/bin/bash

# You must change the value /path/to/susentry.py to the path of your
# susentry.py python file.
export DISPLAY=:0.0
xhost +local:
python3 /path/to/susentry.py -l
exit_status=$?
if [ "${exit_status}" -ne 0 ];
then
    echo "exit ${exit_status}"
    exit 1
fi
echo "EXIT 0"
exit 0

